#A instrução continue é utilizada para pular o restante do bloco de código dentro de um loop e passar para a próxima iteração.

"""for i in range(10):

    if i % 2 == 0:
        continue
    print(i)"""

#Neste exemplo, o loop for itera sobre os números de 0 a 9 utilizando a função range(). Dentro do loop, verifica-se se o número é divisível por 2 utilizando o operador de módulo %. Se o número for divisível por 2 (ou seja, se for par), a instrução continue é executada, fazendo com que o restante do bloco de código seja pulado e passando para a próxima iteração do loop. Como resultado, apenas os números ímpares serão impressos.

